[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
backend.workspace = true
knowledge_space_web.workspace = true
schema.workspace = true
ui.workspace = true

cfg-if.workspace = true

dioxus = { workspace = true, features = ["fullstack", "router"] }

tokio = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true
web-sys.workspace = true

[features]
default = ["server", "web"]
web = ["dioxus/web"]
server = ["dioxus/server", "backend/server"]
