[workspace]
resolver = "2"
members = [
    "backend",
    "schema",
    "ui",

    # platform
    "desktop",
    "mobile",
    "web",
]

[workspace.dependencies]
# workspace
backend = { path = "backend" }
schema = { path = "schema" }
ui = { path = "ui" }

chrono = { version = "0.4.42", features = ["serde"] }
sqlx = { version = "0.8.6", features = ["chrono", "runtime-tokio", "sqlite"] }
tokio = { version = "1.48.0", features = ["full"] }

# axum@0.8 is not yet supported by Dioxus
axum = "0.7.9"
cfg-if = "1.0.3"
cuid2 = "0.1.4"
dioxus = "0.6.3"
fastembed = "5.2.0"
qdrant-client = "1.15.0"
serde = "1.0.228"
# Use after either wasm in dioxus is compatible with rustc 1.89.0
# tailwind-rs-dioxus = "*"
# thiserror = "2.0.17"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
