[workspace]
resolver = "2"
members = [
    "package/backend",
    "package/derive",
    "package/glyph_core",
    "package/knowledge_space_core",
    "package/knowledge_space_web",
    "package/schema",
    "package/ui",

    # platform
    "package/desktop",
    "package/mobile",
    "package/web",
]

[workspace.dependencies]
# Workspace
backend = { path = "package/backend" }
derive = { path = "package/derive" }
glyph_core = { path = "package/glyph_core" }
knowledge_space_core = { path = "package/knowledge_space_core" }
knowledge_space_web = { path = "package/knowledge_space_web" }
schema = { path = "package/schema" }
ui = { path = "package/ui" }

# External
bevy = { version = "0.18.0", default-features = false }
chrono = { version = "0.4.42", features = ["serde"] }
# qdrant-client = { version = "1.15.0", default-features = false }
# sqlx = { version = "0.8.6", features = ["chrono", "runtime-tokio", "sqlite"] }
surrealdb = { version = "2.4.1", features = ["kv-mem"] }
tokio = { version = "1.48.0", features = ["full"] }
web-sys = { version = "0.3.85", features = ["Event", "EventTarget", "Window"] }

cfg-if = "1.0.3"
cuid2 = "0.1.4"
dioxus = "0.7.3"
embed_anything = { path = "../lib/EmbedAnything/rust" }
eyre = "0.6.12"
include_dir = "0.7.4"
ndarray = "0.16"
once_cell = "1.21.3"
pacmap = { version = "0.2", features = ["openblas-system"] }
proc-macro2 = "1.0.103"
quote = "1.0.41"
serde = "1.0.228"
serde_json = "1.0.145"
surrealdb-migrations = "2.4.0"
syn = "2.0.108"
thiserror = "2.0.17"
wasm-bindgen = "0.2.95"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[patch.crates-io]
candle-core = { git = "https://github.com/huggingface/candle", tag = "0.9.1" }
candle-nn = { git = "https://github.com/huggingface/candle", tag = "0.9.1" }
candle-transformers = { git = "https://github.com/huggingface/candle", tag = "0.9.1" }
