app = 'neuramancy'
primary_region = 'sjc'

[build]
image = 'registry.fly.io/neuramancy:latest'

[deploy]
strategy = 'rolling'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024

