[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
schema.workspace = true

dioxus = { workspace = true, features = ["fullstack"] }

cfg-if.workspace = true
eyre.workspace = true
thiserror.workspace = true

axum = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
cuid2 = { workspace = true, optional = true }
fastembed = { workspace = true, optional = true }
qdrant-client = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
surrealdb = { workspace = true, optional = true }
surrealdb-migrations = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
once_cell = { workspace = true, optional = true }

[features]
server = [
    "schema/server",
    "dep:axum",
    "dep:chrono",
    "dep:cuid2",
    "dep:fastembed",
    "dep:once_cell",
    "dep:qdrant-client",
    "dep:sqlx",
    "dep:surrealdb",
    "dep:surrealdb-migrations",
    "dep:tokio",
]
web = ["schema/web"]
