[package]
name = "knowledge_space_web"
version = "0.1.0"
edition = "2024"

[dependencies]
knowledge_space_core.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy = { workspace = true, features = [
  "bevy_asset",
  "bevy_core_pipeline",
  "bevy_pbr",
  "bevy_render",
  "bevy_winit",
  "bevy_window",
  "web",
  "webgl2",
] }
